name: .NET Core CI  

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  

    - name: Setup .NET  
      uses: actions/setup-dotnet@v2  
      with:  
        dotnet-version: '7.0.x'  # Thay đổi phiên bản nếu cần  

    - name: Restore dependencies  
      run: dotnet restore  

    - name: Build  
      run: dotnet build --configuration Release --no-restore  

    - name: Run tests  
      run: dotnet test --no-build --verbosity normal
